name: Continuous Deployment
on: push
jobs:
  Deploy:
    environment:
      name: ${{ github.ref }}
    runs-on: ${{ secrets.RUNNER }}
    steps:
      - name: Deployment
        run: echo "Hello World!"