name: Continuous Deployment
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref }}
    steps:
      - name: Deployment
        env:
          runner: ${{ secrets.RUNNER }}
        shell: bash
        run: echo $runner