name: Continuous Deployment

on: push

jobs:
  environment:
    name: ${{ github.ref }}
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        env:
          runner: ${{ secrets.RUNNER }}
        run: echo $runner
