name: Continuous Deployment

on: push

jobs:
  environment:
    name: ${{ github.ref }}
  
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo env var
        env:
          runner: ${{ secrets.RUNNER }}
        shell: bash
        run: echo $runner